services:
  weiss-dev:
    build:
      target: dev
      args:
        GIT_REPO: ${GIT_REPO}
        GIT_TAG: ${GIT_TAG}
    volumes:
      - .:/app # Mount the source code for development
      - /app/node_modules # Prevent host node_modules from interfering
    image: weiss-dev:${GIT_TAG}
    container_name: weiss-dev
    network_mode: "host"
    environment:
      - NODE_ENV=development
    depends_on:
      - weiss-pvapyws
  weiss-pvapyws:
    build:
      context: ./pvaPyWS
    volumes:
      - ./pvaPyWS:/app
    image: weiss-pvapyws:${GIT_TAG}
    container_name: weiss-pvapyws
    network_mode: "host"
    restart: always
    environment:
      EPICS_DEFAULT_PROTOCOL: ${EPICS_DEFAULT_PROTOCOL}
      EPICS_CA_ADDR_LIST: ${EPICS_CA_ADDR_LIST}
      EPICS_PVA_ADDR_LIST: ${EPICS_PVA_ADDR_LIST}
