services:
  epicswebsuite:
    build:
      target: prod
      args:
        GIT_REPO: ${GIT_REPO}
        GIT_TAG: ${GIT_TAG}
        PROD_PORT: ${PROD_PORT}
    image: epicswebsuite:${GIT_TAG}
    container_name: epicswebsuite
    network_mode: "host"
    environment:
      - NODE_ENV=production
    depends_on:
      - epicswebsuite-pvapyws

  epicswebsuite-pvapyws:
    build:
      context: ./pvaPyWS
    image: epicswebsuite-pvapyws:${GIT_TAG}
    container_name: epicswebsuite-pvapyws
    network_mode: "host"
    restart: always
    environment:
      EPICS_DEFAULT_PROTOCOL: ${EPICS_DEFAULT_PROTOCOL}
      EPICS_CA_ADDR_LIST: ${EPICS_CA_ADDR_LIST}
      EPICS_PVA_ADDR_LIST: ${EPICS_PVA_ADDR_LIST}
