services:
  epicswebsuite:
    build:
      target: prod
      args:
        GIT_REPO: ${GIT_REPO}
        GIT_TAG: ${GIT_TAG}
        PROD_PORT: ${PROD_PORT}
    image: epicswebsuite:${GIT_TAG}
    container_name: epicswebsuite
    network_mode: "host"
    environment:
      - NODE_ENV=production
    depends_on:
      - epicswebsuite-pvapyws

  epicswebsuite-pvapyws:
    build:
      context: ./pvaPy
      args:
        EPICS_DEFAULT_PROTOCOL: pva
        EPICS_CA_ADDR_LIST: "localhost"
        EPICS_PVA_ADDR_LIST: "localhost"
    image: epicswebsuite-pvapyws:${GIT_TAG}
    container_name: epicswebsuite-pvapyws
    network_mode: "host"
    restart: always
