services:
  epicswebsuite-dev:
    build:
      target: dev
      args:
        GIT_REPO: ${GIT_REPO}
        GIT_TAG: ${GIT_TAG}
    volumes:
      - ..:/app # Mount the source code for development
    image: epicswebsuite-dev:${GIT_TAG}
    container_name: epicswebsuite-dev
    network_mode: "host"
    environment:
      - NODE_ENV=development
    depends_on:
      - epicswebsuite-pvws

  epicswebsuite-pvws:
    build:
      context: ./pvws
      args:
        PVWS_SOURCE: ${PVWS_SOURCE}
        PVWS_GIT_TAG: ${PVWS_GIT_TAG}
        PVWS_PORT: ${PVWS_PORT}
    image: epicswebsuite-pvws:${PVWS_DOCKER_TAG}
    container_name: epicswebsuite-pvws
    network_mode: "host"
    restart: always
    volumes:
      - ./pvws/setenv.sh:/usr/local/tomcat/bin/setenv.sh
    healthcheck:
      test: curl -sS http://localhost:${PVWS_PORT}/pvws/ | grep -c "img/connected.png" > /dev/null
      timeout: "5s"
      retries: 10
